interface SeedUser {
  id: string;
  nombre: string;
  apellido: string;
  edad: number;
  ciudad: string;
  correo: string;
  genero: 'masculino' | 'femenino' | 'prefiero no decirlo';
}

interface SeedDataUsers {
  users: SeedUser[];
}

export const initalDataUser: SeedDataUsers = {
  users: [
    {
      id: 'd8e8e3e1-7e4a-4e4b-8e4c-9e4d8e4e8e4f',
      nombre: 'Pedro',
      apellido: 'González',
      edad: 32,
      ciudad: 'Bogotá',
      correo: 'pedro.gonzalez@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p',
      nombre: 'Laura',
      apellido: 'Ramos',
      edad: 23,
      ciudad: 'Medellín',
      correo: 'laura.ramos@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 'q1w2e3r4-t5y6-u7i8-o9p0-a1s2d3f4g5h',
      nombre: 'Gabriel',
      apellido: 'Silva',
      edad: 41,
      ciudad: 'Cali',
      correo: 'gabriel.silva@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'j1k2l3m4-n5b6-v7c8-x9z0-q1w2e3r4t5y',
      nombre: 'Ana',
      apellido: 'García',
      edad: 29,
      ciudad: 'Barranquilla',
      correo: 'ana.garcia@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 'u1i2o3p4-a5s6-d7f8-g9h0-j1k2l3m4n5b',
      nombre: 'Luis',
      apellido: 'Martínez',
      edad: 37,
      ciudad: 'Cartagena',
      correo: 'luis.martinez@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'c5v6b7n8-m9q0-w1e2-r3t4-y5u6i7o8p9a',
      nombre: 'María',
      apellido: 'Hernández',
      edad: 26,
      ciudad: 'Bucaramanga',
      correo: 'maria.hernandez@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 's5d6f7g8-h9j0-k1l2-z3x4-c5v6b7n8m9q',
      nombre: 'Andrés',
      apellido: 'Pérez',
      edad: 45,
      ciudad: 'Pereira',
      correo: 'andres.perez@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'w5e6r7t8-y9u0-i1o2-p3a4-s5d6f7g8h9j',
      nombre: 'Sofía',
      apellido: 'Ramírez',
      edad: 18,
      ciudad: 'Santa Marta',
      correo: 'sofia.ramirez@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 'k5l6z7x8-c9v0-b1n2-m3q4-w5e6r7t8y9u',
      nombre: 'Miguel',
      apellido: 'Gómez',
      edad: 33,
      ciudad: 'Manizales',
      correo: 'miguel.gomez@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'i5o6p7a8-s9d0-f1g2-h3j4-k5l6z7x8c9v',
      nombre: 'Camila',
      apellido: 'Torres',
      edad: 20,
      ciudad: 'Ibagué',
      correo: 'camila.torres@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 'b5n6m7q8-w9e0-r1t2-y3u4-i5o6p7a8s9d',
      nombre: 'David',
      apellido: 'Silva',
      edad: 42,
      ciudad: 'Villavicencio',
      correo: 'david.silva@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'f5g6h7j8-k9l0-z1x2-c3v4-b5n6m7q8w9e',
      nombre: 'Ana',
      apellido: 'Rojas',
      edad: 27,
      ciudad: 'Cúcuta',
      correo: 'ana.rojas@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 'r5t6y7u8-i9o0-p1a2-s3d4-f5g6h7j8k9l',
      nombre: 'Daniel',
      apellido: 'Ortega',
      edad: 38,
      ciudad: 'Pasto',
      correo: 'daniel.ortega@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'v5b6n7m8-q9w0-e1r2-t3y4-u5i6o7p8a9s',
      nombre: 'Laura',
      apellido: 'Jiménez',
      edad: 19,
      ciudad: 'Neiva',
      correo: 'laura.jimenez@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 'd5f6g7h8-j9k0-l1z2-x3c4-v5b6n7m8q9w',
      nombre: 'Carlos',
      apellido: 'Moreno',
      edad: 31,
      ciudad: 'Armenia',
      correo: 'carlos.moreno@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'e5r6t7y8-u9i0-o1p2-a3s4-d5f6g7h8j9k',
      nombre: 'Juan',
      apellido: 'Álvarez',
      edad: 24,
      ciudad: 'Popayán',
      correo: 'juan.alvarez@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'l5z6x7c8-v9b0-n1m2-q3w4-e5r6t7y8u9i',
      nombre: 'Fernando',
      apellido: 'Ramos',
      edad: 35,
      ciudad: 'Valledupar',
      correo: 'fernando.ramos@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'p5a6s7d8-f9g0-h1j2-k3l4-z5x6c7v8b9n',
      nombre: 'María',
      apellido: 'Cruz',
      edad: 17,
      ciudad: 'Montería',
      correo: 'maria.cruz@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 'm5q6w7e8-r9t0-y1u2-i3o4-p5a6s7d8f9g',
      nombre: 'Javier',
      apellido: 'González',
      edad: 28,
      ciudad: 'Sincelejo',
      correo: 'javier.gonzalez@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'h5j6k7l8-z9x0-c1v2-b3n4-m5q6w7e8r9t',
      nombre: 'Sofía',
      apellido: 'Tunja',
      edad: 46,
      ciudad: 'Tunja',
      correo: 'sofia.tunja@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 'y5u6i7o8-p9a0-s1d2-f3g4-h5j6k7l8z9x',
      nombre: 'Pedro',
      apellido: 'Gómez',
      edad: 16,
      ciudad: 'Bogotá',
      correo: 'pedro.gomez@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'c5v6b7n8m9-q0w1-e2r3-t4y5-u6i7o8p9a0s',
      nombre: 'Laura',
      apellido: 'Rodríguez',
      edad: 30,
      ciudad: 'Medellín',
      correo: 'laura.rodriguez@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 'd5f6g7h8j9-k0l1-z2x3-c4v5-b6n7m8q9w0',
      nombre: 'Gabriel',
      apellido: 'González',
      edad: 39,
      ciudad: 'Cali',
      correo: 'gabriel.gonzalez@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'e5r6t7y8u9-i0o1-p2a3-s4d5-f6g7h8j9k0l',
      nombre: 'Ana',
      apellido: 'López',
      edad: 22,
      ciudad: 'Barranquilla',
      correo: 'ana.lopez@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 'q5w6e7r8t9-y0u1-i2o3-p4a5-s6d7f8g9h0j',
      nombre: 'Luis',
      apellido: 'Martínez',
      edad: 40,
      ciudad: 'Cartagena',
      correo: 'luis.martinez@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'k5l6z7x8c9-v0b1-n2m3-q4w5-e6r7t8y9u0i',
      nombre: 'María',
      apellido: 'Hernández',
      edad: 25,
      ciudad: 'Bucaramanga',
      correo: 'maria.hernandez@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 'o5p6a7s8-d9f0-g1h2-j3k4-l5z6x7c8v9b0n',
      nombre: 'Andrés',
      apellido: 'Pérez',
      edad: 48,
      ciudad: 'Pereira',
      correo: 'andres.perez@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'm5q6w7e8r9-t0y1-u2i3-o4p5-a6s7d8f9g0h',
      nombre: 'Sofía',
      apellido: 'Ramírez',
      edad: 16,
      ciudad: 'Santa Marta',
      correo: 'sofia.ramirez@yopmail.com',
      genero: 'femenino',
    },
    {
      id: 'n5b6m7q8w9-e0r1-t2y3-u4i5-o6p7a8s9d0f',
      nombre: 'Miguel',
      apellido: 'Gómez',
      edad: 43,
      ciudad: 'Manizales',
      correo: 'miguel.gomez@yopmail.com',
      genero: 'masculino',
    },
    {
      id: 'g5h6j7k8-l9z0-x1c2-v3b4-n5m6-q7w8e9r0t',
      nombre: 'Camila',
      apellido: 'Torres',
      edad: 19,
      ciudad: 'Ibagué',
      correo: 'camila.torres@yopmail.com',
      genero: 'masculino',
    },
  ],
};
